### ISSUE TITLE
Crash in terraform provider v9.3.6

### ISSUE THREAD

**Issue by kazikfriedrich** [gravitational/teleport-plugins#593]
I'm getting the following output:
```
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).PlanResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).PlanResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).PlanResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).PlanResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).PlanResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).PlanResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).PlanResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-teleport_v9.3.6 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 110 [running]:
github.com/gravitational/teleport-plugins/terraform/tfschema.CopyRoleV5ToTerraform({_, _}, {{0xc000863038, 0x4}, {0x0, 0x0}, {0xc00086303c, 0x2}, {{0xc0002124f8, 0x18}, ...}, ...}, ...)
	/go/src/github.com/gravitational/teleport-plugins/terraform/tfschema/types_terraform.go:12516 +0x2ad89
github.com/gravitational/teleport-plugins/terraform/provider.resourceTeleportRole.Read({{0x1, 0xc00041e690, {0x3b9aca00, 0x12a05f200, _}}}, {_, _}, {{{{0x1318840, 0xc000afb380}, {0xff4480, ...}}, ...}, ...}, ...)
	/go/src/github.com/gravitational/teleport-plugins/terraform/provider/resource_teleport_role.go:184 +0x510
github.com/hashicorp/terraform-plugin-framework/tfsdk.(*server).readResource(0xc0003b3b60, {0x130c0d8, 0xc00083c600}, 0xc00083c4c0, 0xc000777798)
	/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.6.1/tfsdk/serve.go:668 +0x910
github.com/hashicorp/terraform-plugin-framework/tfsdk.(*server).ReadResource(0x130c0d8, {0x130c0d8, 0xc00083c340}, 0x5)
	/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.6.1/tfsdk/serve.go:603 +0x92
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc000158be0, {0x130c180, 0xc000840240}, 0xc0005dc5a0)
	/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov6/tf6server/server.go:744 +0x48c
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x10ff900, 0xc000158be0}, {0x130c180, 0xc000840240}, 0xc0005dc4e0, 0x0)
	/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000152c40, {0x131c068, 0xc00048a1a0}, 0xc000aaf200, 0xc0003b3c50, 0x1b18e50, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000152c40, {0x131c068, 0xc00048a1a0}, 0xc000aaf200, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-teleport_v9.3.6 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2022-06-28T19:06:06.604Z [DEBUG] provider: plugin exited
```

Please note that the tf cache is enabled. This might be related to https://github.com/gravitational/teleport-plugins/issues/555

**Comment by kazikfriedrich** [comment]
Once the roles managed with TF were manually destroyed - `for role in X Y Z; do tctl rm role/$role; done`, the resulting plan had no errors.

**Comment by marcoandredinis** [comment]
Hey @kazikfriedrich 
Thank you for the report

Is the issue reproducible? If so, can you please describe the actions you did?
Per your last comment, it seems you were trying to delete multiple roles

The issue you linked was solved by ensuring we only accept a change when the Teleport's cache is refreshed with the new state.
At the time I also tested for deletions and they worked

**Comment by ArunNadda** [comment]
So in case, a resource (checked with `role`, `saml` and `user`) is modified outside of terraform in such a way that index of an element is higher than original value in `state`, terraform gives this error.

Here are the steps (for a role):
- create a role, with one logins value i.e. logins = ["ubuntu"].
- modify this role to add additional user under logins. (say test).
- terraform plan post this change will give error.


### role in TF file:

```
% cat new_role.tf
resource "teleport_role" "terraform-test" {
  metadata = {
    name        = "terraform-test"
    description = "Terraform test role"
    labels = {
      example  = "yes"
    }
  }

  spec = {
    options = {
      forward_agent           = false
      max_session_ttl         = "30m"
      port_forwarding         = false
      client_idle_timeout     = "1h"
      disconnect_expired_cert = true
      permit_x11_forwarding   = false
      request_access          = "denied"
    }

    allow = {
      logins = ["ubuntu"]

      node_labels = {
         key = ["example"]
         alabel = ["with", "multiple", "values"]
      }
    }

    deny = {
      logins = ["anonymous"]
    }
  }
}
```

### `role` resource created

```

% terraform apply
.
.
.
teleport_saml_connector.saml: Refreshing state... [id=okta_saml]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # teleport_role.terraform-test will be created
  + resource "teleport_role" "terraform-test" {
      + id       = (known after apply)
      + kind     = (known after apply)
      + metadata = {
          + description = "Terraform test role"
          + labels      = {
              + "example" = "yes"
            }
          + name        = "terraform-test"
          + namespace   = (known after apply)
        }
      + spec     = {
          + allow   = {
              + logins      = [
                  + "ubuntu",
                ]
              + node_labels = {
                  + "alabel" = [
                      + "with",
                      + "multiple",
                      + "values",
                    ]
                  + "key"    = [
                      + "example",
                    ]
                }
            }
          + deny    = {
              + logins = [
                  + "anonymous",
                ]
            }
          + options = {
              + cert_format             = (known after apply)
              + client_idle_timeout     = "1h"
              + disconnect_expired_cert = true
              + enhanced_recording      = (known after apply)
              + forward_agent           = false
              + max_session_ttl         = "30m"
              + permit_x11_forwarding   = false
              + port_forwarding         = false
              + request_access          = "denied"
            }
        }
      + version  = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

teleport_role.terraform-test: Creating...
teleport_role.terraform-test: Creation complete after 0s [id=terraform-test]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
%
%
```


### get `role` and add one more `login` user

```
% tctl get role/terraform-test > terraform-test.yaml
% vi terraform-test.yaml

## added test to logins
 % cat terraform-test.yaml
kind: role
metadata:
  description: Terraform test role
  id: 1661915105837631054
  labels:
    example: "yes"
  name: terraform-test
spec:
  allow:
    logins:
    - ubuntu
    - test
    node_labels:
      alabel:
      - with
      - multiple
      - values
      key: example
  deny:
    logins:
    - anonymous
  options:
    cert_format: standard
    client_idle_timeout: 1h0m0s
    desktop_clipboard: false
    disconnect_expired_cert: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 30m0s
    port_forwarding: false
    record_session:
      desktop: true
    request_access: denied
version: v4


% tctl create -f terraform-test.yaml
role 'terraform-test' has been created
```

### `terraform plan` errors out, because it was expecting only one value under `logins` (runtime error: index out of range [1] with length 1)

```
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-teleport plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 185 [running]:
github.com/gravitational/teleport-plugins/terraform/tfschema.CopyRoleV5ToTerraform({0x1058a4dc0, 0x14000630f90}, {{0x14000840000, 0x4}, {0x0, 0x0}, {0x14000840004, 0x2}, {{0x14000840060, 0xe}, ...}, ...}, ...)
	/Users/arunnadda/tickets/terraform_provider_teleport/teleport-plugins/terraform/tfschema/types_terraform.go:12517 +0x2b1ac
github.com/gravitational/teleport-plugins/terraform/provider.resourceTeleportRole.Read({{0x1, 0x1400037c000, {0x3b9aca00, 0x12a05f200, 0xa}}}, {0x1058a4dc0, 0x14000630f90}, {{{{0x1058b3838, 0x14000b2dfb0}, {0x105720fe0, ...}}, ...}, ...}, ...)
	/Users/arunnadda/tickets/terraform_provider_teleport/teleport-plugins/terraform/provider/resource_teleport_role.go:184 +0x4d8
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).readResource(0x1400028e740, {0x1058a4dc0, 0x14000630f90}, 0x1400030b4c0, 0x140005ff780)
	/Users/arunnadda/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.8.0/internal/proto6server/serve.go:724 +0x940
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0x1400028e740, {0x1058a4d18, 0x1400030b440}, 0x1400030b4c0)
	/Users/arunnadda/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.8.0/internal/proto6server/serve.go:651 +0x88
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x140004600a0, {0x1058a4dc0, 0x14000630a20}, 0x140002a9800)
	/Users/arunnadda/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov6/tf6server/server.go:744 +0x4a0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x105829ea0, 0x140004600a0}, {0x1058a4dc0, 0x14000630a20}, 0x140002a97a0, 0x0)
	/Users/arunnadda/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:349 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002b7340, {0x1058b3998, 0x14000373380}, 0x1400000b7a0, 0x14000474960, 0x10608f2b0, 0x0)
	/Users/arunnadda/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xc88
google.golang.org/grpc.(*Server).handleStream(0x140002b7340, {0x1058b3998, 0x14000373380}, 0x1400000b7a0, 0x0)
	/Users/arunnadda/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14000045d40, 0x140002b7340, {0x1058b3998, 0x14000373380}, 0x1400000b7a0)
	/Users/arunnadda/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/arunnadda/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x1f0

Error: The terraform-provider-teleport plugin crashed!
```



## As a workaround, you can follow either of these 2:

1. remove modified (`teleport_role.terraform-test` in my case) resource from terraform state -> import the resource back to terraform state (state will have all the `logins` now) -> Add these `logins` to `.tf` (terraform file) file.

```
terraform state rm teleport_role.terraform-test
terraform import teleport_role.terraform-test terraform-test

# add `login` to main.tf
.
.
    allow = {
      logins = ["ubuntu", "test"]
.
.
```


2. delete manually added `login` from (role) resource  -> now terraform plan/apply can be run (as index is same in tf state) -> add new `logins` to `.tf` file -> terraform apply to change the role/resource.

**Comment by marcoandredinis** [comment]
Thank you so much for the detailed replication steps @ArunNadda 

I'll work on the issue and let you know when it's fixed
